# Generated by Django 4.2.30 on 2026-08-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonial_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='What you can do with this skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class, e.g. fa-brands fa-python', max_length=50),
        ),
    ]
