# Generated by Django 4.2.30 on 2026-08-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill_description_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Larger image shown next to the hero heading', null=True, upload_to='profile/'),
        ),
    ]
