# Generated by Django 4.2.30 on 2026-08-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client',
            field=models.CharField(blank=True, help_text='e.g. Google, Dropbox', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, help_text='e.g. Google, Dropbox', max_length=100),
        ),
    ]
