# Generated by Django 4.2.30 on 2026-08-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_client_project_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='client',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. Senior Software Engineer', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
