# Generated by Django 4.2.30 on 2026-09-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_award_education_interest_language_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Name shown at the top of the resume', max_length=150)),
                ('job_title', models.CharField(blank=True, help_text='e.g. Senior Software Engineer', max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Short career summary paragraph')),
                ('photo', models.ImageField(blank=True, help_text='Profile photo shown on the resume (optional — leave blank to skip)', null=True, upload_to='resume/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, help_text='e.g. +977 98XXXXXXXX', max_length=30)),
                ('location', models.CharField(blank=True, help_text='e.g. Kathmandu, Nepal', max_length=100)),
                ('website', models.URLField(blank=True, help_text='Your portfolio / personal website URL')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('resume_pdf', models.FileField(blank=True, help_text='PDF file for the Download button (optional)', null=True, upload_to='resume/')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resume',
            },
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome class, e.g. fa-brands fa-python', max_length=50),
        ),
        migrations.AddField(
            model_name='award',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='core.resumeprofile'),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='core.resumeprofile'),
        ),
        migrations.AddField(
            model_name='interest',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='core.resumeprofile'),
        ),
        migrations.AddField(
            model_name='language',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='core.resumeprofile'),
        ),
        migrations.AddField(
            model_name='skill',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.resumeprofile'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='core.resumeprofile'),
        ),
    ]
