# Generated by Django 4.2.30 on 2026-09-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resumeprofile_alter_skill_icon_award_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description of what the project does')),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated technologies, e.g. Python, Django, React', max_length=300)),
                ('github_url', models.URLField(blank=True, help_text='Link to the GitHub repository')),
                ('live_url', models.URLField(blank=True, help_text='Link to the live/deployed project (optional)')),
                ('is_open_source', models.BooleanField(default=False, help_text="Show 'Open Source' badge")),
                ('order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.resumeprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
