# Generated by Django 4.2.30 on 2026-09-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_resumeproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name'], 'verbose_name': 'What I do item', 'verbose_name_plural': 'What I do'},
        ),
    ]
